title: ICT Baseline Alignment Framework
email: ictbaseline@gsa.gov
description: >-
  The ICT Baseline Alignment Validation Framework provides 
  test cases as a way for agencies to assess whether their 
  own test processes and use of testing tools cover all Section 508 
  requirements. Two different processes that align to the Baseline 
  should produce the same replicable and reliable test results.

baseurl: ""

primary_navigation:
  - name: Baseline Alignment Home
    url: /
  - name: Contributing
    url: /contributing.html
  - name: Test Cases
    url: /testcases.html
  - name: ICT Baseline (external)
    url: https://ictbaseline.access-board.gov/
    ext: true
plugins:
  - jekyll-feed
  - jekyll-paginate-v2
  - jekyll-redirect-from
  - jekyll-sitemap # See additional instructions for url parameter above.
  - jekyll-seo-tag
